# Personalize sequence names in your output! Add a key (ex: "MGVVGVAPDVVGPDAVAVVGVVGAAVPAAVDVDAVDVVVVVVGGVVVVAAVGVPAPDPVGIP") and assign it a nickname (ex: "Julian")
seq_nicknames = {
    "MGDDDAAPVPVGVGVAGDGAGPGVAPAVVGPAVPADVAVGPAVGDGAPGDAVAVPAPVDVPVAGGLLRRRLLFRVLTRRLVLRRSVGIP": "Allison's sequence", # TODO: Sequence location? Track a sequence across rounds, trace history
    "MGADVVVVVVGVVVGPAAAAPVAAAGPDPDVGPVGVVVAVVPGPVAAVVGVDGVPDVAVVVVDGIP": "A random sequence",
    "MGVGVVDVVVVAVDGAPDVPVAAVGVAVAVVDAAPAPDPAVVGVVGVGDVVAVVVVAVPPVPDPAAGIP": "Curly hair gene (fake)"
}